/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facets */
        get: operations["facets_api_events_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explorer/{database}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_api_explorer__database__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explorer/{database}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description The SQL this change would run, without running it.
         */
        post: operations["preview_api_explorer__database__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explorer/{database}/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tables */
        get: operations["tables_api_explorer__database__tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explorer/{database}/tables/{schema}/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Table */
        get: operations["table_api_explorer__database__tables__schema___table__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explorer/{database}/tables/{schema}/{table}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rows */
        get: operations["rows_api_explorer__database__tables__schema___table__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEvent */
        AuditEvent: {
            /**
             * Changes
             * @default []
             */
            changes: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Id */
            event_id: string;
            /** New */
            new?: {
                [key: string]: unknown;
            } | null;
            /** Operation */
            operation: string;
            /** Previous */
            previous?: {
                [key: string]: unknown;
            } | null;
            /** Request Id */
            request_id?: string | null;
        };
        /** AuditOut */
        AuditOut: {
            /** Delivered */
            delivered: number;
            /** Error */
            error?: string | null;
            /** Events */
            events: components["schemas"]["AuditEvent"][];
            /** Expected */
            expected: number;
            /** Timed Out */
            timed_out: boolean;
            /** Waited Ms */
            waited_ms: number;
        };
        /** ChangeIn */
        ChangeIn: {
            /**
             * Audit
             * @default true
             */
            audit: boolean;
            /**
             * Key
             * @default {}
             */
            key: {
                [key: string]: unknown;
            };
            /**
             * Measure Replicas
             * @default true
             */
            measure_replicas: boolean;
            /**
             * Measure Seconds
             * @default 3
             */
            measure_seconds: number;
            /**
             * Operation
             * @enum {string}
             */
            operation: "INSERT" | "UPDATE" | "DELETE";
            /** Request Id */
            request_id?: string | null;
            /** Schema */
            schema: string;
            /**
             * Service
             * @default dashboard
             */
            service: string;
            /** Table */
            table: string;
            /** User Id */
            user_id: string;
            /**
             * Values
             * @default {}
             */
            values: {
                [key: string]: unknown;
            };
            /**
             * Wait Seconds
             * @default 10
             */
            wait_seconds: number;
        };
        /** ChangeOut */
        ChangeOut: {
            audit: components["schemas"]["AuditOut"] | null;
            /** Operation */
            operation: string;
            replication: components["schemas"]["ReplicationOut"] | null;
            /** Request Id */
            request_id: string;
            route: components["schemas"]["RouteOut"] | null;
            /** Row */
            row: {
                [key: string]: unknown;
            } | null;
            /** Rowcount */
            rowcount: number;
            statement: components["schemas"]["StatementOut"];
        };
        /** ColumnOut */
        ColumnOut: {
            /** Data Type */
            data_type: string;
            /** Generated */
            generated: boolean;
            /** Has Default */
            has_default: boolean;
            /** Name */
            name: string;
            /** Nullable */
            nullable: boolean;
            /** Primary Key */
            primary_key: boolean;
        };
        /** Event */
        Event: {
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["FieldChange"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Db */
            db: string;
            /** Event Id */
            event_id: string;
            /** New */
            new?: {
                [key: string]: unknown;
            } | null;
            /** Operation */
            operation: string;
            /** Previous */
            previous?: {
                [key: string]: unknown;
            } | null;
            /** Request Id */
            request_id?: string | null;
            /** Schema */
            schema: string;
            /** Service */
            service?: string | null;
            /** Table */
            table: string;
            /** User Id */
            user_id?: string | null;
        };
        /** EventPage */
        EventPage: {
            /** Events */
            events: components["schemas"]["Event"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Facets */
        Facets: {
            /** Databases */
            databases: string[];
            /** Operations */
            operations: string[];
            /** Services */
            services: string[];
            /** Tables */
            tables: string[];
            /** Users */
            users: string[];
        };
        /** FieldChange */
        FieldChange: {
            /** After */
            after?: unknown;
            /** Before */
            before?: unknown;
            /** Field */
            field: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Login */
        Login: {
            /** Password */
            password: string;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Audit Problem */
            audit_problem?: string | null;
            /** Audited */
            audited: boolean;
            statement: components["schemas"]["StatementOut"];
        };
        /** ReaderOut */
        ReaderOut: {
            /** Lag Bytes */
            lag_bytes: number | null;
            /** Reader */
            reader: number;
            /** Stale Reads */
            stale_reads: number;
            /** Visible After Ms */
            visible_after_ms: number | null;
        };
        /** ReplicationOut */
        ReplicationOut: {
            /** Fallback Reads */
            fallback_reads: number;
            /** Note */
            note?: string | null;
            /** Readers */
            readers: components["schemas"]["ReaderOut"][];
            /** Timed Out */
            timed_out: boolean;
        };
        /**
         * RouteOut
         * @description Where DBMesh ran a statement, as reported by the proxy.
         */
        RouteOut: {
            /** Duration Us */
            duration_us: number;
            /**
             * Fallback
             * @default false
             */
            fallback: boolean;
            /** Lag Bytes */
            lag_bytes?: number | null;
            /** Reader */
            reader: number;
            /** Reason */
            reason: string;
            /** Target */
            target: string;
        };
        /** RowsOut */
        RowsOut: {
            /** Columns */
            columns: string[];
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            route: components["schemas"]["RouteOut"] | null;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /**
             * Source
             * @enum {string}
             */
            source: "replica" | "primary";
            /** Sql */
            sql: string;
        };
        /**
         * StatementOut
         * @description A statement as it ran: parameterised, and with the values inlined for copying.
         */
        StatementOut: {
            /** Params */
            params: unknown[];
            /** Sql */
            sql: string;
            /** Statement */
            statement: string;
        };
        /** Status */
        Status: {
            /** Audit Available */
            audit_available: boolean;
            /** Databases */
            databases: string[];
        };
        /** TableList */
        TableList: {
            /** Tables */
            tables: components["schemas"]["TableRef"][];
        };
        /** TableOut */
        TableOut: {
            /** Auditable */
            auditable: boolean;
            /** Columns */
            columns: components["schemas"]["ColumnOut"][];
            /** Primary Key */
            primary_key: string[];
            /** Schema */
            schema: string;
            /** Table */
            table: string;
        };
        /** TableRef */
        TableRef: {
            /** Auditable */
            auditable: boolean;
            /** Schema */
            schema: string;
            /** Table */
            table: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_api_events_get: {
        parameters: {
            query?: {
                db?: string | null;
                schema?: string | null;
                table?: string | null;
                operation?: string | null;
                user_id?: string | null;
                request_id?: string | null;
                service?: string | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facets_api_events_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
        };
    };
    get_event_api_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_api_explorer__database__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_explorer__database__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tables_api_explorer__database__tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    table_api_explorer__database__tables__schema___table__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                database: string;
                schema: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rows_api_explorer__database__tables__schema___table__rows_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                source?: "replica" | "primary";
            };
            header?: never;
            path: {
                database: string;
                schema: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
